[project]
name = 'Decentralized-Cultural-Heritage-Digitization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-permission]
path = 'contracts/access-permission.clar'
clarity_version = 2
epoch = 2.5

[contracts.artifact-registration]
path = 'contracts/artifact-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.attribution]
path = 'contracts/attribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.digital-preservation]
path = 'contracts/digital-preservation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
